on:
  push:
    branches:
      - main
      - master
permissions:
  contents: write

name: "check package on main with checklist"

jobs:
  check-package:
    runs-on: ubuntu-latest
    name: "check package"
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: inbo/actions/check_pkg@c5183328c3481a353e1be0ab1b621c294e71b4ce # checklist-0.3.6
